define({
    // Optional text style list in which to override template text styles
    winningNumbersTitle: {
        fontFamily: 'TimesBQ',
        fontWeight: 'normal',
        fontSize: 32,
        fill: 'fontColourLuckyNumberTitle',
        dropShadow: true,
        dropShadowAlpha: 0.7,
        dropShadowAngle: 1.5,
        dropShadowBlur: 3,
        dropShadowDistance: 3,
    },
    playerNumbersTitle: {
        fontFamily: 'TimesBQ',
        fontWeight: 'normal',
        fontSize: 32,
        fill: 'fontColourYourNumberTitle',
        dropShadow: true,
        dropShadowAlpha: 0.7,
        dropShadowAngle: 1.5,
        dropShadowBlur: 3,
        dropShadowDistance: 3,
    },
    winUpToText: {
        fontFamily: 'oswald',
        fontSize: 28,
        fontWeight: 'bold',
        fill: 'fontColourWinUpToTitle',
    },
    bonusLabel: {
        fontFamily: 'TimesBQ',
        fontSize: 32,
        fontWeight: 'normal',
        fill: 'fontColourBonusCover',
        dropShadow: true,
        dropShadowAlpha: 0.7,
        dropShadowAngle: 1.5,
        dropShadowBlur: 3,
        dropShadowDistance: 3,
        padding: 20,
        lineJoin: "round",
        miterLimit: 100,
        lineHeight: 100
    },
    bonusFind3ToEnd: {
        fontFamily: 'TimesBQ',
        fontSize: 30,
        fontWeight: 'normal',
        fill: 'bonusFind3ToEndTextColour',
        dropShadow: true,
        dropShadowAlpha: 0.7,
        dropShadowAngle: 1.5,
        dropShadowBlur: 3,
        dropShadowDistance: 3,
        lineJoin: "round",
        miterLimit: 100,
        lineHeight: 100
    },
    bonusFind3ToWin: {
        fontFamily: 'TimesBQ',
        fontSize: 30,
        fontWeight: 'normal',
        fill: 'bonusFind3ToWinTextColour',
        dropShadow: true,
        dropShadowAlpha: 0.7,
        dropShadowAngle: 1.5,
        dropShadowBlur: 3,
        dropShadowDistance: 3,
        lineJoin: "round",
        miterLimit: 100,
        lineHeight: 100
    },
    winPlaqueValue: {
        fontFamily: 'oswald',
        fontSize: 120,
        fontWeight: 'bold',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    winAllValue: {
        fontFamily: 'oswald',
        fontSize: 120,
        fontWeight: 'bold',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    winUpToValue: {
        fontFamily: 'oswald',
        fontSize: 54,
        fontWeight: 'bold',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusWin6: {
        fontFamily: 'oswald',
        fontSize: 92,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusNoWin6: {
        fontFamily: 'oswald',
        fontSize: 92,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusWin5: {
        fontFamily: 'oswald',
        fontSize: 82,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusNoWin5: {
        fontFamily: 'oswald',
        fontSize: 82,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusWin4: {
        fontFamily: 'oswald',
        fontSize: 72,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusNoWin4: {
        fontFamily: 'oswald',
        fontSize: 72,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusWin3: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusNoWin3: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusWin: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffcf00', '#ffba01', '#ffcf00'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    bonusNoWin: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: ['#ffffff', '#a1a1a2', '#ffffff'],
        fillGradientStops: [0.5, 0.6, 0.8],
    },
    prizeValueNoWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: 'fontColourCashValueNoWin',
        dropShadow: true,
        dropShadowAlpha: 0.7,
        dropShadowAngle: 1.5,
        dropShadowBlur: 3,
        dropShadowDistance: 3,
    },
    prizeValueWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: 'fontColourCashValueWin',
        dropShadow: true,
        dropShadowAlpha: 0.7,
        dropShadowAngle: 1.5,
        dropShadowBlur: 3,
        dropShadowDistance: 3,
    },

    buyButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: 'buyButtonEnabledFontColour',
        padding: 10,
        dropShadow: true,
        dropShadowColor: "#821baa",
        dropShadowBlur: 8,
        dropShadowDistance: 0,
    },
    buyButtonDisabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: 'buyButtonDisabledFontColour',
        padding: 10,
        dropShadow: true,
        dropShadowColor: "#821baa",
        dropShadowBlur: 8,
        dropShadowDistance: 0,
    },
    buyButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: 'buyButtonOverFontColour',
        padding: 10,
        dropShadow: true,
        dropShadowColor: "#821baa",
        dropShadowBlur: 8,
        dropShadowDistance: 0,
    },
    buyButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 41,
        fill: 'buyButtonPressedFontColour',
        padding: 10,
        dropShadow: true,
        dropShadowColor: "#821baa",
        dropShadowBlur: 8,
        dropShadowDistance: 0,
    },
});