define({
    plaqueMessageSmall: {},
    buttonText: {},

    winningNumbersTitle: {
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fontSize: 32,
        fill: 'fontColourLuckyNumberTitle',
    },
    playerNumbersTitle: {
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fontSize: 32,
        fill: 'fontColourYourNumberTitle',
    },

    prizeValueNoWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: 'fontColourCashValueNoWin',
    },
    prizeValueWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: 'fontColourCashValueWin',
    },

    winUpToText: {
        fontFamily: 'oswald',
        fontSize: 28,
        fontWeight: 'bold',
        fill: 'fontColourWinUpToTitle',
    },

    winUpToValue: {
        fontFamily: 'oswald',
        fontSize: 54,
        fontWeight: 'bold',
        fill: 'fontColourWinUpToTitle',
    },

    bonusWin6: {
        fontFamily: 'oswald',
        fontSize: 92,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour',
    },
    bonusNoWin6: {
        fontFamily: 'oswald',
        fontSize: 92,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour',
    },
    bonusWin5: {
        fontFamily: 'oswald',
        fontSize: 82,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour',
    },
    bonusNoWin5: {
        fontFamily: 'oswald',
        fontSize: 82,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour',
    },
    bonusWin4: {
        fontFamily: 'oswald',
        fontSize: 72,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour',
    },
    bonusNoWin4: {
        fontFamily: 'oswald',
        fontSize: 72,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour',
    },
    bonusWin3: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour',
    },
    bonusNoWin3: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour',
    },
    bonusWin: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour',
    },
    bonusNoWin: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour',
    },
    losePlaqueBody: {
        fontFamily: 'oswald',
        fontSize: 70,
        fontWeight: 'bold',
        align: 'center',
        fill: 'fontColourEndOfGameMessageNoWinBodyText',
        padding: 20,
        lineJoin: "round",
        miterLimit: 100,
        lineHeight: 100,
    },
    winPlaqueBody: {
        fontFamily: 'oswald',
        fontSize: 60,
        fontWeight: 'bold',
        align: 'center',
        fill: 'fontColourEndOfGameMessageWinBodyText',
        padding: 10,
    },
    winPlaqueValue: {
        fontFamily: 'oswald',
        fontSize: 120,
        fontWeight: 'bold',
        fill: 'fontColourEndOfGameMessageWinValue',
        padding: 10,
    },
    winAllBody: {
        fontFamily: 'oswald',
        fontSize: 60,
        fontWeight: 'bold',
        align: 'center',
        fill: 'fontColourWinAllMessageWinBodyText',
        padding: 10,
    },
    winAllValue: {
        fontFamily: 'oswald',
        fontSize: 120,
        fontWeight: 'bold',
        fill: 'fontColourWinAllMessageWinValue',
        padding: 10,
    },
    bonusLabel: {
        fontFamily: 'oswald',
        fontSize: 32,
        fontWeight: 'bold',
        fill: 'fontColourBonusCover',
    },
    bonusFind3ToEnd: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: 'bonusFind3ToEndTextColour',
    },
    bonusFind3ToWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: 'bonusFind3ToWinTextColour',
    },

    buyButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: 'buyButtonEnabledFontColour',
        padding: 10,
    },
    buyButtonDisabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: 'buyButtonDisabledFontColour',
        padding: 10,
    },
    buyButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: 'buyButtonOverFontColour',
        padding: 10,
    },
    buyButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 41,
        fill: 'buyButtonPressedFontColour',
        padding: 10,
    },
});